name: Docker Image - Payment Service

# This workflow created docker images, upload them in the DockerHub and run the containers for the BE
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

# Login with Docker Hub, so that docker images are store and available there instead of locally
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
# Get Current Date    
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Test with environment variables
      run: echo $DATE
      env:
        DATE: ${{ steps.date.outputs.date }}  

# Build Docker Image  and upload it to Docker Hub
    - name: Build the Docker image Payments
      run: | 
        docker build --build-arg JAR_FILE=payments-service-example.jar -t payments-service-example:$(DATE)
        docker image push payments-service-example:$DATE
        docker run -d payments-service-example:$DATE

 
