name: Docker Image - Payment Service

# This workflow created docker images, upload them in the DockerHub and run the containers for the BE
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

# Login with Docker Hub, so that docker images are store and available there instead of locally
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
# Build Docker Image  and upload it to Docker Hub
    - name: Build the Docker image Payments
      env:
        USERNAME: devopsp23
        SERVICE_NAME: ${{vars.SERVICE_NAME}}
        TIME_STAMP: ${{ steps.date.outputs.date }}
      run: | 
        echo "$USERNAME/$SERVICE_NAME:$TIME_STAMP"
        docker build  --build-arg JAR_FILE=payments-service-example.jar -tag devopsp23/$SERVICE_NAME:$TIME_STAMP
        docker image push devopsp23/$SERVICE_NAME:$TIME_STAMP
        docker run -d devopsp23/$SERVICE_NAME:$TIME_STAMP
       

 
